version: '2'
services:
  app:
    image: nwops/release_manager
    build: .
    entrypoint:
      - bash
    environment:
      GEM_HOME: '/home/appuser/.gems'
      BUNDLE_PATH: '/home/appuser/.bundle'
      GITLAB_API_ENDPOINT: 'http://web/api/v3'
      # the token may change so this really needs to be more dynamic
      GITLAB_API_PRIVATE_TOKEN: 'A_zJJfgE8P-8mFGK2_r9'
      R10K_REPO_URL: "git@web:devops/control-repo.git"
    working_dir: /app
    volumes:
      - .:/app

  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://web'
    ports:
      - '8000:80'
      - '4433:443'
      - '2201:22'
    volumes:
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'

# setup ssh key in gitlab
